INSERT INTO items(name, comment) VALUES('Bratislava', 'some comment');
INSERT INTO items(name, comment) VALUES('Budapest', 'some comment');
INSERT INTO items(name, comment) VALUES('Prague', 'some comment');
INSERT INTO items(name, comment) VALUES('Warsaw', 'some comment');
INSERT INTO items(name, comment) VALUES('Los Angeles', 'some comment');
INSERT INTO items(name, comment) VALUES('Los Angeles', 'some comment');
INSERT INTO items(name, comment) VALUES('New York', 'some comment');
INSERT INTO items(name, comment) VALUES('Edinburgh', 'some comment');
INSERT INTO items(name, comment) VALUES('Berlin', 'some comment');
INSERT INTO items(name, comment) VALUES('Debilsk', 'some comment 2');